version: 1
builder:
  configs:
  - documentation_targets:
    - SharingGRDB
    - SharingGRDBCore
    - StructuredQueriesGRDB
    - StructuredQueriesGRDBCore
    custom_documentation_parameters: [--enable-experimental-overloaded-symbol-presentation]
