import CloudKit

@available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
// @Table("sharing_grdb_cloudkit_records")
struct Record {
  var zoneName: String
  var recordName: String
  // @Column(as: CKRecord?.DataRepresentation.self)
  var lastKnownServerRecord: CKRecord?
  var localModificationDate: Date?
}

// NB: This is generated by inlining the above macro applications.
@available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
extension Record: StructuredQueriesCore.Table {
  public struct TableColumns: StructuredQueriesCore.TableDefinition {
    public typealias QueryValue = Record
    public let zoneName = StructuredQueriesCore.TableColumn<QueryValue, String>("zoneName", keyPath: \QueryValue.zoneName)
    public let recordName = StructuredQueriesCore.TableColumn<QueryValue, String>("recordName", keyPath: \QueryValue.recordName)
    public let lastKnownServerRecord = StructuredQueriesCore.TableColumn<QueryValue, CKRecord?.DataRepresentation>("lastKnownServerRecord", keyPath: \QueryValue.lastKnownServerRecord)
    public let localModificationDate = StructuredQueriesCore.TableColumn<QueryValue, Date?>("localModificationDate", keyPath: \QueryValue.localModificationDate)
    public static var allColumns: [any StructuredQueriesCore.TableColumnExpression] {
      [QueryValue.columns.zoneName, QueryValue.columns.recordName, QueryValue.columns.lastKnownServerRecord, QueryValue.columns.localModificationDate]
    }
  }
  public static let columns = TableColumns()
  public static let tableName = "sharing_grdb_cloudkit_records"
  public init(decoder: inout some StructuredQueriesCore.QueryDecoder) throws {
    let zoneName = try decoder.decode(String.self)
    let recordName = try decoder.decode(String.self)
    let lastKnownServerRecord = try decoder.decode(CKRecord?.DataRepresentation.self)
    self.localModificationDate = try decoder.decode(Date.self)
    guard let zoneName else {
      throw QueryDecodingError.missingRequiredColumn
    }
    guard let recordName else {
      throw QueryDecodingError.missingRequiredColumn
    }
    guard let lastKnownServerRecord else {
      throw QueryDecodingError.missingRequiredColumn
    }
    self.zoneName = zoneName
    self.recordName = recordName
    self.lastKnownServerRecord = lastKnownServerRecord
  }
}
