import StructuredQueriesCore

/// A row in the temporary `sqlitedata_undo_log` table, which stores inverse SQL statements
/// generated by undo triggers.
@Table("sqlitedata_undo_log")
package struct UndoLog {
  package static var schemaName: String? { "temp" }

  /// Auto-incremented sequence number (the SQLite rowid alias).
  package let seq: Int
  /// The table name whose row change produced this inverse SQL entry.
  package let tableName: String
  /// The affected rowid in `tableName`.
  package let trackedRowID: Int
  /// A SQL statement that inverts the original change.
  package let sql: String
}
